apiVersion: v1
kind: Service
metadata: 
  name: backend
  labels:
    app: backend
spec:
  type: NodePort
  selector: 
    app: backend
  ports:
    - port: 5050
      targetPort: 5050
      nodePort: 30050

